### ISSUE TITLE
Move challenge channels into threads

### ISSUE THREAD

**Issue by es3n1n** [hfz1337/Eruditus#16]
~~Once we reach the limit of 50 channels in a category, the challenge puller thread stops, which is annoying. I suggest that we create a new category automatically to continue adding channels when this happens. So, that in the end we could have multiple categories for the one CTF. Please note that these changes could also break features like `archivectf` and others.~~

https://github.com/hfz1337/Eruditus/issues/16#issuecomment-1702655725

**Comment by hfz1337** [comment]
A permanent solution that I had in mind for a while was to move challenge channels into threads, but at the time private threads could only be created by nitro users (if I'm not mistaken). I just checked again, and private threads are now unlocked for everyone (you can have up to 1000 active threads in the server).
Threads are more convenient and will make things way more organized (we will only have 1 channel per category which contains as many threads as challenges in that category).

**Comment by es3n1n** [comment]
> A permanent solution that I had in mind for a while was to move challenge channels into threads, but at the time private threads could only be created by nitro users (if I'm not mistaken). I just checked again, and private threads are now unlocked for everyone (you can have up to 1000 active threads in the server). Threads are more convenient and will make things way more organized (we will only have 1 channel per category which contains as many threads as challenges in that category).

Oh yes, absolutely. Sounds a lot better than what i proposed

**Comment by hfz1337** [comment]
We can indicate whether a category is completed using something similar to the picture below, this will allow everyone in the CTF to know the progress of each category.
![image](https://github.com/hfz1337/Eruditus/assets/32499116/4b6fb53b-42a6-4c40-b7e8-23026ccee299)
