### ISSUE TITLE
Export archived CTF channels into HTML form

### ISSUE THREAD

**Issue by hfz1337** [hfz1337/Eruditus#33]
After archiving a CTF, at some point in the future we may need to delete its channels in order to save space, before this deletion process it would be great to export the entirety of its channels/threads in HTML form as a static website.

We can even add a microservice that hosts these static websites so we don't need to download them in order to view them.

**Comment by dnx04** [comment]
please make this possible as fast as possible

**Comment by es3n1n** [comment]
> please make this possible as fast as possible

https://github.com/hfz1337/Eruditus/pulls

**Comment by hfz1337** [comment]
> please make this possible as fast as possible

A few challenges with this feature, not planned for anytime sooner, but you can use https://github.com/Tyrrrz/DiscordChatExporter in the meantime if you want to export chat logs.

**Comment by hfz1337** [comment]
Closed in 4598e1ba
