### ISSUE TITLE
CTFtime unreachable due to CloudFlare

### ISSUE THREAD

**Issue by hfz1337** [hfz1337/Eruditus#46]
[CTFtime](https://ctftime.org) recently enabled CloudFlare to prevent scraping the website, this breaks the feature that pulls leaderboard and ranking changes, they didn't add a challenge for API endpoints though.

**Comment by es3n1n** [comment]
Seems like they disabled it ~12 hours ago, we still don't have some of the API methods to retrieve everything Eruditus needs. so I guess there's no other approach for now.

**Comment by hfz1337** [comment]
Yes, mainly for the leaderboard tracking feature and the other project that scrapes the write-ups. I'll close this for now hoping they don't enable it again.
