### ISSUE TITLE
Auto account creation 

### ISSUE THREAD

**Issue by ouxs-19** [hfz1337/Eruditus#7]
Because most ctfs use ctfd, I believe it is conceivable to have the bot establish an account for that ctf (assuming it uses ctfd).

This will also necessitate the addition of configuration for the email address that will be used in the registration process, as well as any other information that may be required (depends on what the registration requires).

**Comment by hfz1337** [comment]
Thanks Oussama, this was already added in f508fb315d20474c79dc20287418d741c38d2444.
On my test guild, it works properly without any bugs, but I've seen it failing in CE server, I'll investigate the issue, I also appreciate any help in reproducing the bug.

For now, it only supports registrations with the 3 default fields: username, email and password, but people can add custom fields in CTFd. Furthermore, this will of course fail in the presence of ReCaptcha.

Regarding CTFs that require email confirmation, we should implement that feature as well, it's easy to do with Gmail.

**Comment by hfz1337** [comment]
Should be fixed in 58702076d71d46a56f5274fc672d48b206677013.
