### ISSUE TITLE
Add a command to set the CTF reminder channel

### ISSUE THREAD

**Issue by malikDaCoda** [hfz1337/Eruditus#8]
Currently the bot sends CTF reminders to the channel defined as `REMINDER_CHANNEL` in the configuration variables, and if the variable is not set, it looks up a channel named `#general` or the first world-readable channel it can write to.
It would be good to have a command to set the reminder channel manually.

**Comment by hfz1337** [comment]
Added in 7c6405e452e8f5fe3000dd758ff3a8f1cfe62730.
